#!/bin/sh

target_dir="/etc/asterisk"
#extensions.conf
valtasip=$(grep valtasip "$__object/explorer/extensions.conf" || true)
if [ "$valtasip" = "" ]; then
   echo "cat >> $target_dir/extensions.conf << EOF"
   echo '[valtasip]'
   echo 'exten => _.,1,NoOp(IM receiving)'
   echo '	same => n,NoOp(To \$(MESSAGE(to)))'
   echo '	same => n,NoOp(From \$(MESSAGE(from)))'
   echo '	same => n,NoOp(Body \$(MESSAGE(body)))'
   echo '	same => n,Set(ACTUALTO=\${CUT(MESSAGE(to),@,1)})'
   echo '	same => n,MessageSend(\${ACTUALTO},\${MESSAGE(from)})'
   echo '	same => n,NoOp(Send status is \${MESSAGE_SEND_STATUS})'
   echo '	same => n,Hangup()'
   echo 'EOF'
fi
#extconfig.conf
sippeers=$(grep '^sippeers => mysql,general,sip_buddies' "$__object/explorer/extconfig.conf" || true)
if [ "$sippeers" = "" ]; then
   echo "echo 'sippeers => mysql,general,sip_buddies' >> $target_dir/extconfig.conf"
fi
sipusers=$(grep '^sipusers => mysql,general,sip_buddies' "$__object/explorer/extconfig.conf" || true)
if [ "$sipusers" = "" ]; then
   echo "echo 'sipusers => mysql,general,sip_buddies' >> $target_dir/extconfig.conf"
fi
#sip.conf
valtasip=$(grep '^context=valtasip' "$__object/explorer/sip.conf" || true)
if [ "$valtasip" = "" ]; then
   echo "sed -i 's/^context=[^ \t]\+/context=valtasip/g' $target_dir/sip.conf"
fi
tlsenable=$(grep '^tlsenable=yes' "$__object/explorer/sip.conf" || true)
if [ "$tlsenable" = "" ]; then
   echo "sed -i 's/^[;]\?tlsenable=[^ \t]\+/tlsenable=yes/g' $target_dir/sip.conf"
fi
tlsbindaddr=$(grep '^tlsbindaddr=0\.0\.0\.0' "$__object/explorer/sip.conf" || true)
if [ "$tlsbindaddr" = "" ]; then
   echo "sed -i 's/^[;]\?tlsbindaddr=[^ \t]\+/tlsbindaddr=0.0.0.0/g' $target_dir/sip.conf"
fi
transport=$(grep '^transport=tls' "$__object/explorer/sip.conf" ||  true)
if [ "$transport" = "" ]; then
   echo "sed -i 's/^transport=[^ \t]\+/transport=tls/g' $target_dir/sip.conf"
fi
tlscertfile=$(grep '^tlscertfile=/var/lib/asterisk/keys/asterisk.pem' "$__object/explorer/sip.conf" || true)
if [ "$tlscertfile" = "" ]; then
    echo "sed -i 's,^[;]\?tlscertfile=[^ \t]\+,tlscertfile=/var/lib/asterisk/keys/asterisk.pem,g' $target_dir/sip.conf"
fi
tlscafile=$(grep '^tlscafile=/var/lib/asterisk/keys/ca.crt' "$__object/explorer/sip.conf" || true)
if [ "$tlscafile" = "" ]; then
    echo "sed -i 's,^[;]\?tlscafile=[^ \t]\+,tlscafile=/var/lib/asterisk/keys/ca.crt,g' $target_dir/sip.conf"
fi
tlsdontverifyserver=$(grep '^tlsdontverifyserver=yes' "$__object/explorer/sip.conf" || true)
if [ "$tlsdontverifyserver" = "" ]; then
   echo "sed -i 's/^[;]\?tlsdontverifyserver=[^ \t]\+/tlsdontverifyserver=yes/g' $target_dir/sip.conf"
fi
tlscipher=$(grep '^tlscipher=ALL' "$__object/explorer/sip.conf" || true)
if [ "$tlscipher" = "" ]; then
   echo "sed -i 's/^[;]\?tlscipher.*/tlscipher=ALL/g' $target_dir/sip.conf"
fi
rtcachefriends=$(grep '^rtcachefriends=no' "$__object/explorer/sip.conf" || true)
if [ "$rtcachefriends" = "" ]; then
   echo "sed -i 's/^[;]\?rtcachefriends=[^ \t]\+/rtcachefriends=no/g' $target_dir/sip.conf"
fi
#res_config_mysql.conf
mysql_server=$(cat "$__object/parameter/mysql_server")
server=$(grep "dbhost = $mysql_server" "$__object/explorer/res_config_mysql.conf" || true)
if [ "server" = "" ]; then
    echo "sed -i \"s/^;dbhost = [^ \t]\+/dbhost = $mysql_server/g\" $target_dir/res_config_mysql.conf"
fi
mysql_port=$(cat "$__object/parameter/mysql_port")
port=$(grep "dbhost = $mysql_port" "$__object/explorer/res_config_mysql.conf" || true)
if [ "port" = "" ]; then
    echo "sed -i \"s/^;dbport = [^ \t]\+/dbport = $mysql_port/g\" $target_dir/res_config_mysql.conf"
fi
mysql_username=$(cat "$__object/parameter/mysql_username")
mysql_password=$(cat "$__object/parameter/mysql_password")
mysql_dbname=$(cat "$__object/parameter/mysql_dbname")
